# Generated by Django 5.0.7 on 2024-07-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0021_alter_post_id_alter_profile_id_alter_replie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replie',
            name='reply_content',
            field=models.CharField(max_length=50000),
        ),
    ]
